version: '3.8'

services:
  task-management-app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - app.env
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: task-management-db
    restart: always
    env_file:
      - bd.env
    ports:
      - "5433:5432"